### ISSUE TITLE
Selected tab blanks (Possible bug?)

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#14]
Running on FPP 6.1.1, fresh install on Pi4, whichever tab is selected gets blanked out. I'm unsure if this is a bug or a browser setting causing the colors to match. I've attached a pic of what I'm seeing. Thanks!

<img width="458" alt="Screen Shot 2022-11-02 at 9 06 21 AM" src="https://user-images.githubusercontent.com/1048868/199541585-dda4ef18-6331-4e66-bea8-eaf1d5be5583.png">

**Comment by jcrossbdn** [comment]
fixed. thanks for the report!

**Comment by nmiller0113** [comment]
Looks good @jcrossbdn, thanks!

**Comment by nmiller0113** [comment]
@jcrossbdn, not sure if I can reopen this case but I found another strange issue...not sure if it's related but can open another case if needed. As I noted in [this comment](https://github.com/jcrossbdn/fpp-after-hours/issues/15#issuecomment-1301183868), I just did a fresh fpp test install. When I installed the plugin the selected tab showed blank again (this was a brand new fpp and plugin install). It wasn't until I checked the "Internet Radio is the After Hours Music Source" button, did the tab show the blanking correction you had previously made. One other thing...I also can't figure out a way to uncheck the "Internet Radio is the After Hours Music Source" button. I uncheck it and hit save and leave and come back and it's checked again. I was trying to uncheck it to see if it changed the selected tab to blank again.

Sorry to keep hitting ya with things :)

**Comment by jcrossbdn** [comment]
I wonder if there was some caching in your browser that reset once the form was submitted.  The style fix is in a place that should load every time the tabs are shown.The source checkbox can’t be unchecked because there is no other source coded into the plug-in yet (no local audio/non streaming source).  Once it is turned on the first time it is stored in the config and can’t be removed. :)JasonSent from my iPhoneOn Nov 2, 2022, at 3:32 PM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn, not sure if I can reopen this case but I found another strange issue...not sure if it's related but can open another case if needed. As I noted in this comment, I just did a fresh fpp test install. When I installed the plugin the selected tab showed blank again (this was a brand new fpp and plugin install). It wasn't until I checked the "Internet Radio is the After Hours Music Source" button, did the tab show the blanking correction you had previously made. One other thing...I also can't figure out a way to uncheck the "Internet Radio is the After Hours Music Source" button. I uncheck it and hit save and leave and come back and it's checked again. I was trying to uncheck it to see if it changed the selected tab to blank again.
Sorry to keep hitting ya with things :)

**Comment by nmiller0113** [comment]
@jcrossbdn I thought it may have been browser related as well and even went from chrome to firefox where I had completely deleted all history and cache (forever). It still did the same thing until I checked the "Internet Radio is the After Hours Music Source" box. Also, did you see my message that I cannot uncheck that box now? Just making sure you saw that. Thanks!

**Comment by jcrossbdn** [comment]
@nmiller0113 Not being able to uncheck that box was actually expected behavior because the only two options were supposed to be local audio or internet audio for the plugin.  I have now removed the local tab and that button and told the config init function to default to internet since that is all that's available anyway.

I haven't been able to reproduce the transparency issue on any of my pi's now, so hopefully it is solved.

**Comment by nmiller0113** [comment]
Thanks @jcrossbdn, after we're done with the troubleshooting in the other case, I'll try to reproduce it again on another fresh install.
