### ISSUE TITLE
Fade volume in/out at start/stop (Feature Request)

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#17]
Hi @jcrossbdn, I was wondering how hard it would be to get the volume to fade in/out when the script is started or stopped. To make it so it isn't so abrupt? Since there is volume control built into the plugin, I'm hoping this is fairly simple to do. Thanks!

**Comment by jcrossbdn** [comment]
@nmiller0113 I think I have worked this out. It was a little bit of figuring but I am going to test it on my show tonight to make sure it doesn't stop the show from starting properly.  There is a risk that it could prevent fpp audio so this is a little touchy but if it works it will be something the user will have to configure in their playlist instead of the plugin itself.

Basically in the script command for either the start or stop scripts you will be able to add args "fade <max seconds> <minimum volume>".  *obviously this won't work until I release the code and you upgrade the plugin*

Max seconds will be how many seconds the fade will happen over and it uses steps of 5%.  If the max seconds doesn't compute a reasonable timeframe for performing the fade then it will hard cut/set as soon as time is almost elapsed.

I am adding minimum volume because for me I wouldn't want it to go below 20% on fade out and would want it to start at 30% for a fade in.  I found it annoying that there was basically no audio coming out once it got to 20% so it didn't make sense to allow it to continue stepping down further.

**Comment by nmiller0113** [comment]
Thanks @jcrossbdn, I'm looking forward to hearing the results!

**Comment by jcrossbdn** [comment]
My test failed tonight but since the show has been done for the night I have been playing with it and I believe I have figured out a solution that I will test in production tomorrow night.  The script worked perfectly until it was run through the fpp scheduler at which point it would not fade out but rather hard cut.  It seems adding a 1 second delay in the stop script itself appears to solve this but I have no idea why, lol.  The start script with fade worked 100% though.

**Comment by jcrossbdn** [comment]
My testing has worked every time I try it (even a test schedule) but has failed every time my actual show has started.  I cannot isolate an issue so I've pushed it to github so others can do some testing with it to see if we can narrow down any possible issues. Worst thing that happens is mpd hard cuts out like it always has.  I'm not sure if this is related to the script being called last in my playlist lead in after turning projectors on and disabling my porch light but I can't imagine how that would play a role. I haven't published instructions for it in github yet so here they are (use at your own risk knowing I can't really support it but would like to know your findings and success rate): *please make sure to update to the latest fpp-after-hours version released 2022-12-05 around 22:30 CST.

In the script entry that runs "fpp-after-hours-stop.php" in the fpp playlist editor click on edit and add the following to the Args line: fade 10 20
where 10 is the number of seconds the fade should be over and 20 is the minimum volume percent level that should be achieved.  Also turn on Blocking or you will have issues with fpp not starting your show.

In the script entry that runs "fpp-after-hours-start.php" in the fpp playlist editor click on edit and add the following to the Args line: fade 10 30
where 10 is the number of seconds the fade should be over and 30 is the starting mpd volume. The volume will ramp up to the volume listed in the fpp-after-hours plugin page.  Blocking should not be required for this entry.

![image](https://user-images.githubusercontent.com/10160178/205815598-8517571f-1088-475a-92d0-5b7b087bfb1e.png)

**Comment by jcrossbdn** [comment]
I noticed some errors in the fppd error log relating to my porch lights because I had not configured them after the 6.2 upgrade.  Removed those two entries in my playlist and the fade out worked perfectly tonight.

**Comment by nmiller0113** [comment]
Thanks Jason. I’ve not had a chance to test but definitely will tomorrow.
Excited to hear!

Nathan

**Comment by nmiller0113** [comment]
@jcrossbdn I just tested it a ton, and it worked great. I did see a couple of times where it cut off the fade timer and either went straight to off (stop script) or straight to full (start script)...but that only happened three times, and I'm not sure whether it was due to me testing too quickly...but I didn't run them back to back, and I always let them run their full fade times. Not sure of the cause, but I wanted you to be aware. Otherwise, 98% of my tests ran great!

I did start with your fade settings, but I ended up landing on "fade 15 1" for both my fade in and fade out...but that was just my preference! Thank you again for your work on this! I'll let you know if I find any other issues.

**Comment by nmiller0113** [comment]
@jcrossbdn, been working great for over a week now. Mission accomplished! Thank you again! I hope that you and your family have a great holiday season!

**Comment by jcrossbdn** [comment]
Glad to hear it!  I ended up taking it off my show because it messed up once and fpp couldn’t take over the audio so my show played for 20 minutes with no audio before I caught it (usb sound card). I even had a failsafe entry that was just running the off script again after the fade. Something went wonky with how fpp ran the scripts, almost like blocking didn’t work that time.I’ll do up the documentation on the help page on how to use it but will have to have the disclaimer to “use at your own risk”.Thanks so much for the feedback on your success with it!  Was a nice little challenge to figure out how to accomplish it.JasonSent from my iPhoneOn Dec 15, 2022, at 3:13 PM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn, been working great for over a week now. Mission accomplished! Thank you again! I hope that you and your family have a great holiday season!
