### ISSUE TITLE
Not an issue, just wanted to say THANK YOU!

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#24]
I would have emailed, but don't have your email address :)

I've been using this for two years on two different FPP version installs 6.x/7.x, and it's worked flawlessly. Both last year and this year, I broadcast all year long using this plugin and literally never have had as much as a hiccup. It just keeps going and going, and I've never even had to restart it. It literally ran 11 months without a restart last year and the only reason I did restart it was because I was doing an FPP update. Thank you for the work on this plugin. Not only is it stable/solid, you're super responsive to not just issues, but also requests...two of which were mine and they've been awesome!

Happy New Year!

**Comment by jcrossbdn** [comment]
Hi Nathan!So fantastic to hear that!  I appreciate the feedback.  Developers only ever hear about the issues:)It’s funny you mentioned that it just goes and goes.  I left my pi running after the Christmas show completed last year (Jan 13th) and when I logged in to get the show running in November it was still playing the after hours stream, same as you said yours did, through internet outages and everything:)I’m hoping again to update the interface a little this coming year and possibly add local media as well… but I’ve been saying that since fpp v6 came out with the new user interface, haha.A very happy new year to you and yours also!JasonSent from my iPhoneOn Jan 9, 2024, at 6:03 PM, Nathan MIller ***@***.***> wrote:﻿
I would have emailed, but don't have your email address :)
I've been using this for two years on two different FPP version installs 6.x/7.x, and it's worked flawlessly. Both last year and this year, I broadcast all year long using this plugin and literally never have had as much as a hiccup. It just keeps going and going, and I've never even had to restart it. It literally ran 11 months without a restart last year and the only reason I did restart it was because I was doing an FPP update. Thank you for the work on this plugin. Not only is it stable/solid, you're super responsive to not just issues, but also requests...two of which were mine and they've been awesome!
Happy New Year!
