### ISSUE TITLE
After Hours Music Plugin Does not Play

### ISSUE THREAD

**Issue by blainebertrand** [jcrossbdn/fpp-after-hours#6]
After installing the plug, setting a streaming source and it shows "reachable" I am still not able to play when testing. 

I have the Check box for "active" selected and I can click on "run start script" and it acts like it is trying to play, but after a second or two, it goes back to "no music is playing". 

I tried removing and adding the script back, but that did not have any affect. In fact, not sure it truly removed the plug in because all of my stream sources were still there after reinstalling it. 

What is the best method to troubleshoot this?

Thanks so much!

**Comment by blainebertrand** [comment]
I should mention this is FPP 3.5.1.

**Comment by jcrossbdn** [comment]
Daniel Kulp found a bug tonight that was impacting BBB devices and I have made the correction so it is possible that if you do a plugin update now it may work for you.

If this doesn't work then the other common issue is a bad stream URL.  I would first go through the help document at https://github.com/jcrossbdn/fpp-after-hours/blob/master/README.md#finding-the-url-of-your-favorite-internet-radio-station and if that still doesn't work for you then feel free to send me the stream URL you are trying to use and I'll check it out.  I have so far been unsuccessful in programatically validating that stream URL's are valid.

You may also want to try a known working stream url... Here is the one I'm using this year: http://167.114.64.181:8232

The "reachable" indicator is really only checking that the domain is pingable and does not validate the stream.

The uninstall script will leave the fpp-after-hours config file but should delete everything else related to the plugin.  I did this mostly because when I was developing it I found it really annoying to have to type in the stream details every time:)

Jason

**Comment by blainebertrand** [comment]
Thank you for the feedback. I just tried the update plugin and FPP says there are not any updates available for the plugin.

Sorry for the trouble.

BB


[cid:image003.png@01D5A64C.3CF2FB60]



Blaine Bertrand<mailto:beb@texas-show.com>
    Production Manager
806-655-2181 (w)  |  806-236-2200 (m)
Buy tickets @ www.texas-show.com<http://www.texas-show.com/peo>

**Comment by jcrossbdn** [comment]
okay no worries I'd try using the known working stream I provided above and see if that works next.  If not then I'll likely have to do a little more troubleshooting with you if your game.  Are you using a PI or a BBB?

**Comment by jcrossbdn** [comment]
Closing since I haven't heard anything more on this.

**Comment by blainebertrand** [comment]
Jason,

Sorry I did not respond. I guess I overlooked the email somehow. I did not realize you had responded again. I have been in parade mode lately and not had a chance to check again, other than to say, I did try another Pie fresh and got the same results that day. I will give this a shot again later this week.

Thanks,
Blaine

**Comment by blainebertrand** [comment]
Jason,

Finally got a chance re-read the thread last night and found that I am not still not getting anything to work so far. I have tried a few different links from the site you show in the read me.

I also tried the link you sent for the help document, but that link doesn’t appear to work.

In the thread, you mention I should use the use the stream that you had provided earlier, yet when I looked back, I didn’t see any threads referenced, unless I accidentally deleted that part of the conversation (some times I get a little delete happy on my phone).

Thanks for your time.

Blaine

**Comment by blainebertrand** [comment]
Forgive me. You can ignore my last diatribe. While the link for the help did not work, there was one thing in the information for setup on the Github site that I overlooked and just noticed it. I have it working now. I am so sorry for bothering you on something right in front of me.

Thank you again for your help and patience.

Blaine

**Comment by jcrossbdn** [comment]
Hmm I’ll check the help link. It should be just a hyperlink to github.

Glad to hear you have it working now:)

It’s not a bother as long as it works in the end!

Jason

**Comment by jcrossbdn** [comment]
I looked at the help link and it appears to be working properly.  Not sure what is going on that you couldn't access it.
